spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/hellouniverse_db
    username: hellouniverse_db_user
    password: ${DB_PASSWORD}

  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
